platform :ios, '9.0'
 use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'
target "AVCaptureDome" do
    
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
pod 'AFNetworking', "~> 2.5.4"
pod 'Masonry'
#pod 'LookinServer', :configurations => ['Debug']
##pod 'MBProgressHUD'
# pod 'OOMDetector' , :configurations => ['Debug']
end
